<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="TheSingularityWorkshop.FSM_COS" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" /><PackageReference Include="coverlet.collector" Version="10.0.1"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference><PackageReference Include="xunit" Version="2.9.3" /><PackageReference Include="xunit.runner.visualstudio" Version="3.0.0" />
    <PackageReference Include="TheSingularityWorkshop.ProtocolAi" Version="0.1.0-alpha.2" />
    <PackageReference Include="TheSingularityWorkshop.GrammarAi" Version="0.1.0-alpha.1" />
    <PackageReference Include="TheSingularityWorkshop.GUI.Core" Version="0.1.0-alpha.3" /></ItemGroup>
  <ItemGroup><ProjectReference Include="..\..\src\FSM_COS\FSM_COS.csproj" /></ItemGroup>
</Project>
